### ISSUE TITLE
Incorrect UI behavior

### ISSUE THREAD

**Issue by sadov** [AnaraAbd/ITMO_project#3]
Cancel button in dialog windows not handled -- application still run and at the last phase application without any data entered in inputbox widgets shows info-window "TRANSACTION number is:" with message "All updates are complete." Can this be fixed?

After entering of wrong data (sender, receiver, amount or password) I see info-window "TRANSACTION number is:" with message "All updates are complete." again, but transaction was not happen. During the running of shell-script in debug mode I see error message from geth like this:

Ethereum Wallet Transfer Transaction Error: invalid address at web3.js:3879:15 at web3.js:3705:20 at web3.js:4948:28 at map (<native code>) at web3.js:4947:12 at web3.js:4973:18 at web3.js:4998:23 at <anonymous>:1:1

Seems like "<" redirection sign in message -- the root of problem, without it message shows correctly. Is it possible to remove <> redirection symbols from error message before using in 'dialog' program?

**Comment by AnaraAbd** [comment]
Fixed
